/*
 * SpaceApi Validator
 *
 * This is the SpaceApi Validator api
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spaceapivalidatorclient

// ValidateV1Response struct for ValidateV1Response
type ValidateV1Response struct {
	Valid   bool   `json:"valid"`
	Message string `json:"message"`
}
