/*
 * SpaceApi Validator
 *
 * This is the SpaceApi Validator api
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spaceapivalidatorclient

// SchemaError struct for SchemaError
type SchemaError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}
