/*
 * SpaceApi Validator
 *
 * This is the SpaceApi Validator api
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spaceapivalidatorclient
// ServerInformation struct for ServerInformation
type ServerInformation struct {
	Description string `json:"description"`
	Usage string `json:"usage"`
	Version string `json:"version"`
}
