/*
 * SpaceApi Validator
 *
 * This is the SpaceApi Validator api
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spaceapivalidatorclient
// ValidateV1 struct for ValidateV1
type ValidateV1 struct {
	Data map[string]interface{} `json:"data"`
}
