/*
 * SpaceApi Validator
 *
 * This is the SpaceApi Validator api
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spaceapivalidatorclient
// ValidateUrlV2 struct for ValidateUrlV2
type ValidateUrlV2 struct {
	Url string `json:"url"`
}
